// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Use DIRECT_URL for CLI (migrate, db push); use DATABASE_URL only if DIRECT_URL is not set (e.g. no pooler).
  datasource: {
    url: process.env["DIRECT_URL"] ?? env("DATABASE_URL"),
  },
});
